name: restaurant_app
description: "This project is a fully-featured Flutter application designed to enhance the dining experience for users and streamline restaurant operations."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk:
      flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  google_fonts: ^6.2.1
  http: ^1.2.2
  path_provider: ^2.1.5
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

  test: ^1.25.8
  mocktail: ^1.0.4
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/loading.json
    - assets/error_anim.json
    - assets/icon/app_icon.png
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

